name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"  # chạy tự động mỗi ngày 00:00 UTC
  workflow_dispatch:      # cho phép bấm nút "Run workflow"
  push:
    branches: ["main"]    # chạy khi có push vào branch main

permissions:
  contents: write         # cho phép push lên nhánh output

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ndlabdev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
